---
name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: builder
          load: true
      - name: Run
        run: |
          patch -p1 -d ice < 0001-OpenSSL-3.0-build-See-zeroc-ice-ice-1320.patch
          mkdir dist
          docker run --rm -e CPPFLAGS='-Wno-error=use-after-free -Wno-error=c++20-compat -Wno-error=template-id-cdtor -Wno-error=deprecated-declarations -Wno-error=unused-result -Wno-error=register' -v $PWD/dist:/opt -v $PWD/ice:/build builder /bin/bash -c "cd /build/cpp ; make install"
          cd dist
          tar zcf Ice-3.6.5-rocky10-x86_64.tar.gz Ice-3.6.5
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/*.tar.gz
          if-no-files-found: error
      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        
      - name: Download artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: artifacts
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.timestamp.outputs.timestamp }}
          name: "Release ${{ steps.timestamp.outputs.timestamp }}"
          body: "Automated release created on ${{ steps.timestamp.outputs.timestamp }}"
          draft: false
          prerelease: false
          files: |
            artifacts/*.tar.gz
